version: '3'
services:
  node1:
    image: "wandgibaut/python_codelet"
    volumes:
      - ./nodes/node1/:/home/node
    network_mode: host
    environment:
      - ROOT_NODE_DIR=/home/node
    command: /home/node/nodeMaster.sh 127.0.0.1:9998

  node2:
    image: "wandgibaut/python_codelet"
    volumes:
      - ./nodes/node2/:/home/node
    network_mode: host
    environment:
      - ROOT_NODE_DIR=/home/node
    command: /home/node/nodeMaster.sh 127.0.0.1:9996

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    network_mode: host