version: '3'
services:
  sensory:
    image: "python_codelet"
    volumes:
      - ./codelets/sensory/:/home
    depends_on:
      - mongodb
    network_mode: host
    command: /home/codelet/methods/run.sh

  perceptual:
    image: "python_codelet"
    volumes:
      - ./codelets/perceptual/:/home
    depends_on:
      - mongodb
    network_mode: host
    command: /home/codelet/methods/run.sh
  
  behavioral:
    image: "python_codelet"
    volumes:
      - ./codelets/behavioral/:/home
    depends_on:
      - mongodb
    network_mode: host
    command: /home/codelet/methods/run.sh
    
  motor:
    image: "python_codelet"
    volumes:
      - ./codelets/motor/:/home
    depends_on:
      - mongodb
    network_mode: host
    command: /home/codelet/methods/run.sh
  
  
  touchMemories:
    image: "python_codelet"
    volumes:
      - ./:/home
    depends_on:
      - mongodb
    network_mode: host
    command: /home/start_mind.sh

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    network_mode: host