version: '3'
services:
  sensory:
    image: "python_codelet"
    volumes:
      - ./codelets/sensory/:/home
    network_mode: host
    command: /home/codelet/methods/run.sh

  perceptual:
    image: "python_codelet"
    volumes:
      - ./codelets/perceptual/:/home
    ports:
      - "9999:9999"
      - "9998:9998"
    network_mode: host
    command: /home/codelet/methods/run.sh 192.168.0.12:9999 192.168.0.12:9998
  
  touchMemories:
    image: "python_codelet"
    volumes:
      - ./:/home
    network_mode: host
    command: /home/start_mind.sh

  redis:
    image: "redis:alpine"
    network_mode: host