version: '3'
services:
  sensory:
    image: "wandgibaut/python_codelet"
    volumes:
      - ./codelets/sensory/:/home
    network_mode: host
    environment:
      - ROOT_CODELET_DIR=/home/codelet
    command: /home/codelet/methods/run.sh localhost:9998

  perceptual:
    image: "wandgibaut/python_codelet"
    volumes:
      - ./codelets/perceptual/:/home
    network_mode: host
    environment:
      - ROOT_CODELET_DIR=/home/codelet
    command: /home/codelet/methods/run.sh 127.0.0.1:9997

  behavioral:
    image: "wandgibaut/python_codelet"
    volumes:
      - ./codelets/behavioral/:/home
    network_mode: host
    environment:
      - ROOT_CODELET_DIR=/home/codelet
    command: /home/codelet/methods/run.sh 127.0.0.1:9996

  motor:
    image: "wandgibaut/python_codelet"
    volumes:
      - ./codelets/motor/:/home
    network_mode: host
    environment:
      - ROOT_CODELET_DIR=/home/codelet
    command: /home/codelet/methods/run.sh 127.0.0.1:9995
  
  #touchMemories:
  #  image: "wandgibaut/python_codelet"
  #  volumes:
  #    - ./:/home
  #  network_mode: host
  #  environment:
  #    - ROOT_CODELET_DIR=/home/codelet
  #  command: /home/create_memories.sh
